# Generated by Django 4.1.2 on 2022-10-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Post',
        ),
    ]
