# Generated by Django 4.1.2 on 2022-11-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
