# Generated by Django 4.1.2 on 2022-11-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='like',
        ),
    ]
