# Generated by Django 4.1.2 on 2022-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='i.jpg', upload_to='static/img'),
        ),
    ]
