# Generated by Django 4.1.2 on 2022-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/i.jpg', upload_to='img/blog'),
        ),
    ]
