# Generated by Django 4.1.2 on 2022-11-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='process',
        ),
    ]
