# Generated by Django 4.1.2 on 2022-11-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_like_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dlikes',
            field=models.IntegerField(default=0),
        ),
    ]
