# Generated by Django 4.1.2 on 2022-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_dlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.CharField(default='', max_length=10),
        ),
    ]
