# Generated by Django 4.1.2 on 2022-11-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='totalviews',
            field=models.IntegerField(default=0),
        ),
    ]
