# Generated by Django 4.1.2 on 2022-11-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_totalviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fnlikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='fntotalviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='fnviews',
            field=models.IntegerField(default=0),
        ),
    ]
