# Generated by Django 4.1.2 on 2022-11-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_post_fnlikes_post_fntotalviews_post_fnviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fnlikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fntotalviews',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fnviews',
        ),
    ]
