# Generated by Django 4.1.2 on 2022-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_post_fnlikes_remove_post_fntotalviews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('ftotalviews', models.IntegerField(default=0)),
                ('fviews', models.IntegerField(default=0)),
                ('flikes', models.IntegerField(default=0)),
            ],
        ),
    ]
