# Generated by Django 4.1.2 on 2022-11-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_fpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FPost',
        ),
    ]
