# Generated by Django 4.1.2 on 2022-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_delete_fpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/img/blog/a.jpg', upload_to='blog/images'),
        ),
    ]
