# Generated by Django 4.1.2 on 2022-11-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/img/a.jpg', upload_to='blog/images'),
        ),
    ]
