# Generated by Django 4.1.2 on 2022-11-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
