# Generated by Django 4.1.2 on 2022-11-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbsup',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('thumb', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
