# Generated by Django 4.1.2 on 2022-11-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_thumbsup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbsup',
        ),
    ]
