# Generated by Django 4.1.2 on 2022-11-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_thubsup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thubsup',
        ),
    ]
